//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18010
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moo.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Moo.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 D:\UploadedFiles\ 的本地化字符串。
        /// </summary>
        public static string File_UploadPath {
            get {
                return ResourceManager.GetString("File_UploadPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 104857600 的本地化字符串。
        /// </summary>
        public static string MooTester_CompileMemory {
            get {
                return ResourceManager.GetString("MooTester_CompileMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;color:red&gt;*您程序恶心得让编译器不住地吐槽*&lt;/color&gt; 的本地化字符串。
        /// </summary>
        public static string MooTester_CompileOLE {
            get {
                return ResourceManager.GetString("MooTester_CompileOLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;color:red&gt;*内存太小，不够编译器折腾*&lt;/color&gt; 的本地化字符串。
        /// </summary>
        public static string MooTester_CompilerMLE {
            get {
                return ResourceManager.GetString("MooTester_CompilerMLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;color:red&gt;*编译器生气了：*
        ///{{&quot;{0}&quot;}}&lt;/color&gt; 的本地化字符串。
        /// </summary>
        public static string MooTester_CompilerRE {
            get {
                return ResourceManager.GetString("MooTester_CompilerRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;color:green&gt;*编译成功*&lt;/color&gt; 的本地化字符串。
        /// </summary>
        public static string MooTester_CompilerSuccess {
            get {
                return ResourceManager.GetString("MooTester_CompilerSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;color:red&gt;*编译器太磨叽，等不及了*&lt;/color&gt; 的本地化字符串。
        /// </summary>
        public static string MooTester_CompilerTLE {
            get {
                return ResourceManager.GetString("MooTester_CompilerTLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;color:red&gt;*等等，编译器闹肚子了。*&lt;/color&gt; 的本地化字符串。
        /// </summary>
        public static string MooTester_CompilerUndefinedError {
            get {
                return ResourceManager.GetString("MooTester_CompilerUndefinedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 8000 的本地化字符串。
        /// </summary>
        public static string MooTester_CompileTime {
            get {
                return ResourceManager.GetString("MooTester_CompileTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;color:red&gt;*评测机貌似出去遛弯了……*&lt;/color&gt; 的本地化字符串。
        /// </summary>
        public static string MooTester_NetworkError {
            get {
                return ResourceManager.GetString("MooTester_NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 5000 的本地化字符串。
        /// </summary>
        public static string MooTester_SocketSendTimeout {
            get {
                return ResourceManager.GetString("MooTester_SocketSendTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 104857600 的本地化字符串。
        /// </summary>
        public static string MooTester_TestAnswerOnlyMemory {
            get {
                return ResourceManager.GetString("MooTester_TestAnswerOnlyMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2000 的本地化字符串。
        /// </summary>
        public static string MooTester_TestAnswerOnlyTime {
            get {
                return ResourceManager.GetString("MooTester_TestAnswerOnlyTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 # *[url:测试点#{0}|?page=testCase&amp;id={0}]* 的本地化字符串。
        /// </summary>
        public static string MooTester_TestCaseX {
            get {
                return ResourceManager.GetString("MooTester_TestCaseX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;color:red&gt;比较器抽风了~&lt;/color&gt; 的本地化字符串。
        /// </summary>
        public static string MooTester_TestCompareError {
            get {
                return ResourceManager.GetString("MooTester_TestCompareError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 127.0.0.1 的本地化字符串。
        /// </summary>
        public static string MooTester_TesterIP {
            get {
                return ResourceManager.GetString("MooTester_TesterIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 6000 的本地化字符串。
        /// </summary>
        public static string MooTester_TesterPort {
            get {
                return ResourceManager.GetString("MooTester_TesterPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (得分*{0}*，用时*{1}ms*，内存*{2}byte(s)*) {{&quot;{3}&quot;}} 的本地化字符串。
        /// </summary>
        public static string MooTester_TestInfo {
            get {
                return ResourceManager.GetString("MooTester_TestInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;color:purple&gt;内存超出限制。&lt;/color&gt; 的本地化字符串。
        /// </summary>
        public static string MooTester_TestMLE {
            get {
                return ResourceManager.GetString("MooTester_TestMLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;color:cyan&gt;程序吐槽过多。&lt;/color&gt; 的本地化字符串。
        /// </summary>
        public static string MooTester_TestOLE {
            get {
                return ResourceManager.GetString("MooTester_TestOLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;color:orange&gt;程序崩溃。&lt;/color&gt; 的本地化字符串。
        /// </summary>
        public static string MooTester_TestRE {
            get {
                return ResourceManager.GetString("MooTester_TestRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;color:green&gt;正确。&lt;/color&gt; 的本地化字符串。
        /// </summary>
        public static string MooTester_TestSuccess {
            get {
                return ResourceManager.GetString("MooTester_TestSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;color:darkred&gt;超出时间限制。&lt;/color&gt; 的本地化字符串。
        /// </summary>
        public static string MooTester_TestTLE {
            get {
                return ResourceManager.GetString("MooTester_TestTLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;color:gray&gt;天气不好，程序不开心。&lt;/color&gt; 的本地化字符串。
        /// </summary>
        public static string MooTester_TestUndefinedError {
            get {
                return ResourceManager.GetString("MooTester_TestUndefinedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;color:red&gt;答案错误。&lt;/color&gt; 的本地化字符串。
        /// </summary>
        public static string MooTester_TestWA {
            get {
                return ResourceManager.GetString("MooTester_TestWA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 D:\v-Judge_Kernel\Special_Judge.exe 的本地化字符串。
        /// </summary>
        public static string MooTester_TranditionalJudger {
            get {
                return ResourceManager.GetString("MooTester_TranditionalJudger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;color:red&gt;*不支持{0}语言*&lt;/color&gt; 的本地化字符串。
        /// </summary>
        public static string MooTester_UnsupportedLanguage {
            get {
                return ResourceManager.GetString("MooTester_UnsupportedLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;color:red&gt;*{0}语言不支持{1}操作*&lt;/color&gt; 的本地化字符串。
        /// </summary>
        public static string MooTester_UnsupportedLanguageOperation {
            get {
                return ResourceManager.GetString("MooTester_UnsupportedLanguageOperation", resourceCulture);
            }
        }
    }
}
